/**
 * Bathymetry, and the biomes that follow from it.
 *
 * The sea floor is a *function*, not a mesh: floorHeightAt(x, z) returns the
 * depth analytically, the visible terrain is generated by sampling it, and so is
 * every gameplay query. Nothing raycasts against terrain to find the ground.
 *
 * The shape of that function is modelled on a real continental margin rather
 * than on concentric rings, so depth is no longer just distance from the middle:
 *
 *   - a shallow SHELF around the origin, gently sloping,
 *   - a SHELF BREAK where it drops away into deep water,
 *   - SEAMOUNTS that rise back up out of the deep, some almost to the light,
 *   - a TRENCH that cuts across the whole map, far deeper than anything else,
 *   - a BASIN that the trench feeds into.
 *
 * Biomes are then assigned by what the sea floor actually *is* at a point -
 * its depth, whether it sits on a seamount, whether it lies in the trench - so
 * a coral reef grows on a sunlit seamount top a long way out, and the deepest
 * water can be found closer in than some of the shallowest.
 */
(function (SL) {
  'use strict';

  let SEED = 20260912;

  const BIOMES = [
    {
      id: 'shallows', name: 'Safe Shallows',
      floorColor: new THREE.Color(0.86, 0.80, 0.60),
      waterColor: new THREE.Color(0.10, 0.55, 0.62),
      fogDensity: 0.012,
      scrapDensity: 0, stalkerDensity: 0,
      flora: ['seagrass', 'coralFan'], floraDensity: 0.9
    },
    {
      id: 'kelp', name: 'Kelp Forest',
      floorColor: new THREE.Color(0.34, 0.38, 0.24),
      waterColor: new THREE.Color(0.06, 0.30, 0.26),
      fogDensity: 0.030,
      scrapDensity: 1.6, stalkerDensity: 0.5,
      flora: ['kelp', 'kelp', 'seagrass'], floraDensity: 2.0
    },
    {
      id: 'plateau', name: 'Grassy Plateau',
      floorColor: new THREE.Color(0.42, 0.52, 0.30),
      waterColor: new THREE.Color(0.05, 0.28, 0.34),
      fogDensity: 0.034,
      scrapDensity: 0.4, stalkerDensity: 0.18,
      flora: ['seagrass', 'seagrass', 'boulder'], floraDensity: 1.2
    },
    {
      // Now grows on the sunlit tops of seamounts, wherever they rise.
      id: 'coral', name: 'Coral Seamount',
      floorColor: new THREE.Color(0.62, 0.26, 0.22),
      waterColor: new THREE.Color(0.14, 0.30, 0.40),
      fogDensity: 0.028,
      scrapDensity: 0.3, stalkerDensity: 0.12,
      flora: ['coralFan', 'coralTube', 'coralTube'], floraDensity: 1.8
    },
    {
      // The slopes: rubble shed off the shelf break and the seamount flanks.
      id: 'boulders', name: 'Boulder Slope',
      floorColor: new THREE.Color(0.30, 0.31, 0.33),
      waterColor: new THREE.Color(0.06, 0.13, 0.22),
      fogDensity: 0.040,
      scrapDensity: 0.3, stalkerDensity: 0.2,
      flora: ['boulder', 'boulder', 'glowPod'], floraDensity: 1.0
    },
    {
      id: 'crystal', name: 'Crystal Caverns',
      floorColor: new THREE.Color(0.34, 0.20, 0.30),
      waterColor: new THREE.Color(0.16, 0.06, 0.18),
      fogDensity: 0.038,
      scrapDensity: 0.25, stalkerDensity: 0.12,
      flora: ['crystal', 'crystal', 'boulder'], floraDensity: 1.3,
      crystalDensity: 1.6
    },
    {
      id: 'trench', name: 'Deep Trench',
      floorColor: new THREE.Color(0.12, 0.12, 0.15),
      waterColor: new THREE.Color(0.012, 0.035, 0.075),
      fogDensity: 0.070,
      scrapDensity: 0.2, stalkerDensity: 0.1,
      flora: ['glowPod', 'boulder'], floraDensity: 0.6
    },
    {
      id: 'kings', name: "King's Basin",
      floorColor: new THREE.Color(0.20, 0.17, 0.12),
      waterColor: new THREE.Color(0.05, 0.04, 0.03),
      fogDensity: 0.050,
      scrapDensity: 1.0, stalkerDensity: 0.35,
      flora: ['boulder', 'glowPod', 'crystal'], floraDensity: 0.8
    },
    {
      // A drowned plateau a long way offshore, shallow enough for kelp. The
      // only forest out here, and it belongs to something.
      id: 'farkelp', name: "Kelper's Reach",
      floorColor: new THREE.Color(0.26, 0.34, 0.20),
      waterColor: new THREE.Color(0.05, 0.22, 0.20),
      fogDensity: 0.030,
      scrapDensity: 0.5, stalkerDensity: 0.15,
      flora: ['kelp', 'kelp', 'kelp', 'seagrass'], floraDensity: 2.4
    },
    {
      id: 'abyss', name: 'Abyssal Plain',
      floorColor: new THREE.Color(0.10, 0.14, 0.18),
      waterColor: new THREE.Color(0.02, 0.07, 0.12),
      fogDensity: 0.030,
      scrapDensity: 0.15, stalkerDensity: 0,
      flora: ['glowPod', 'boulder'], floraDensity: 0.5
    }
  ];

  const byId = {};
  BIOMES.forEach((b, i) => { b.index = i; byId[b.id] = b; });

  // --- Features placed once per world, from the seed -------------------------

  let seamounts = [];
  let kingBasin = null;
  let whaleGround = null;
  let farBank = null;

  function placeFeatures() {
    seamounts = [];

    // Nine seamounts out past the shelf break, scattered all the way to the
    // rim. There were five when the map was a good deal smaller; left at five,
    // everything past the slope was one unbroken plain.
    for (let i = 0; i < 9; i++) {
      const angle = SL.hash(i, 11, SEED) * Math.PI * 2;
      const radius = SL.lerp(120, 345, SL.hash(i, 22, SEED));
      seamounts.push({
        x: Math.cos(angle) * radius,
        z: Math.sin(angle) * radius,
        // Three of them are tall enough to break into sunlight.
        rise: SL.lerp(34, 62, SL.hash(i, 33, SEED)) * (i < 3 ? 1.25 : 0.85),
        width: SL.lerp(30, 54, SL.hash(i, 44, SEED))
      });
    }

    // The king sits in a basin gouged out beyond the trench.
    const kingAngle = SL.hash(7, 77, SEED) * Math.PI * 2;
    kingBasin = {
      x: Math.cos(kingAngle) * 248,
      z: Math.sin(kingAngle) * 248,
      radius: 52
    };

    // The whale works open water on the far side of the map from the king.
    whaleGround = {
      x: Math.cos(kingAngle + Math.PI) * 235,
      z: Math.sin(kingAngle + Math.PI) * 235,
      radius: 72
    };

    // The far bank: a plateau rising out of the abyss, a long swim from
    // anywhere, carrying the only kelp forest outside the shelf.
    const bankAngle = SL.hash(13, 131, SEED) * Math.PI * 2;
    farBank = {
      x: Math.cos(bankAngle) * 322,
      z: Math.sin(bankAngle) * 322,
      radius: 78,
      rise: 64
    };
  }

  /** How far the far bank lifts the floor at a point, in metres. */
  function bankRise(x, z) {
    if (!farBank) return 0;
    const d = Math.hypot(x - farBank.x, z - farBank.z) / farBank.radius;
    if (d > 2.2) return 0;
    return farBank.rise * Math.exp(-d * d * 1.5);
  }

  /** How far into the trench a point lies, 0 outside to 1 at the axis. */
  function trenchInfluence(x, z) {
    // The trench wanders across the whole map rather than ringing the middle.
    const axis = Math.sin(x * 0.0085) * 110 + Math.sin(x * 0.023) * 22;
    const distance = Math.abs(z - axis);
    const halfWidth = 40 + Math.sin(x * 0.015) * 11;

    // A submarine canyon: it bites well into the shelf rather than beginning
    // out in deep water, so there is deep water close to home and shallow water
    // a long way from it.
    const offshore = SL.smoothstep((Math.hypot(x, z) - 42) / 38);
    return (1 - SL.smoothstep(distance / halfWidth)) * offshore;
  }

  /** Combined seamount rise at a point, in metres. */
  function seamountRise(x, z) {
    let rise = 0;
    for (const mount of seamounts) {
      const dx = x - mount.x;
      const dz = z - mount.z;
      const d = Math.sqrt(dx * dx + dz * dz) / mount.width;
      if (d < 2.4) rise += mount.rise * Math.exp(-d * d);
    }
    return rise;
  }

  /** The underlying continental margin: shelf, shelf break, abyssal slope. */
  function marginProfile(r) {
    if (r < 140) {
      // The shelf, sloping gently away from the shallows. It is wide, because
      // the shelf is where the game is - kelp, scrap and stalkers all live here.
      return -3.5 - Math.pow(r / 140, 1.7) * 13;
    }
    if (r < 250) {
      // The shelf break: the floor falls away fast.
      return SL.lerp(-16.5, -66, SL.smoothstep((r - 140) / 110));
    }
    // The abyssal slope beyond it, still descending, but slowly.
    return -66 - (r - 250) * 0.06;
  }

  function floorHeightAt(x, z) {
    const r = Math.hypot(x, z);
    let y = marginProfile(r);

    // Seamounts rise out of whatever is underneath them, and so does the bank.
    y += seamountRise(x, z);
    y += bankRise(x, z);

    // The king's basin is gouged below the surrounding floor.
    if (kingBasin) {
      const d = Math.hypot(x - kingBasin.x, z - kingBasin.z) / kingBasin.radius;
      if (d < 1.6) y -= 26 * Math.exp(-d * d * 1.6);
    }

    // The trench cuts through everything, deepest of all.
    const trench = trenchInfluence(x, z);
    if (trench > 0.001) y -= trench * trench * 62;

    // Dunes and detail, gentler in deep water than on the shelf.
    const relief = SL.lerp(1.0, 3.2, SL.clamp((-y) / 60, 0, 1));
    y += SL.fbm(x, z, 4, 0.032, 2.0, 0.5, SEED) * relief * 2.4;
    y += SL.fbm(x, z, 3, 0.21, 2.3, 0.45, SEED + 977) * relief * 0.7;

    return Math.min(y, SL.WATER_LEVEL - 2.2);
  }

  /** Which biome the sea floor at this point belongs to. */
  function biomeAt(x, z) {
    const y = floorHeightAt(x, z);
    const depth = -y;

    // Region noise separates kelp from open grass, and marks crystal country.
    const region = SL.fbm(x, z, 3, 0.011, 2.1, 0.5, SEED + 4001);
    const mineral = SL.fbm(x, z, 2, 0.008, 2.0, 0.5, SEED + 8101);

    if (kingBasin && Math.hypot(x - kingBasin.x, z - kingBasin.z) < kingBasin.radius) {
      return byId.kings;
    }

    // The trench is the trench regardless of how deep the floor around it is.
    if (trenchInfluence(x, z) > 0.45 && depth > 34) return byId.trench;

    // The far bank's shallows are kelp; its flanks are rubble.
    const bank = bankRise(x, z);
    if (bank > 18) return depth < 34 ? byId.farkelp : byId.boulders;

    // A seamount top in the light is a reef; its flanks are rubble.
    const rise = seamountRise(x, z);
    if (rise > 12) return depth < 26 ? byId.coral : byId.boulders;

    if (depth < 6.5) return byId.shallows;
    if (depth < 17) return region > -0.22 ? byId.kelp : byId.shallows;
    if (depth < 27) return region > -0.05 ? byId.kelp : byId.plateau;
    if (depth < 38) return region > 0.25 ? byId.boulders : byId.plateau;
    // Crystal country is meant to be somewhere you find, not the floor of half
    // the ocean - so the mineral noise has to run well above average for it.
    if (depth < 56) return mineral > 0.24 ? byId.crystal : byId.boulders;
    if (depth < 76) return mineral > 0.34 ? byId.crystal : byId.abyss;
    return byId.abyss;
  }

  const _c = new THREE.Color();
  function floorColorAt(x, z) {
    const biome = biomeAt(x, z);
    _c.copy(biome.floorColor);
    const mottle = SL.fbm(x, z, 2, 0.4, 2, 0.5, SEED + 313) * 0.12;
    return _c.multiplyScalar(1 + mottle);
  }

  // --- The spawn index -------------------------------------------------------
  //
  // Biomes no longer occupy tidy rings, so "a random point in this biome" is
  // answered by sampling the whole map once at world build and bucketing the
  // results. The same pass feeds the minimap, so the map you navigate by is
  // literally the map the world was populated from.

  const INDEX_RESOLUTION = 150;
  let index = null;

  function buildIndex() {
    const step = (SL.WORLD_RADIUS * 2) / INDEX_RESOLUTION;
    const cells = new Array(INDEX_RESOLUTION * INDEX_RESOLUTION);
    const buckets = {};
    for (const biome of BIOMES) buckets[biome.id] = [];

    for (let iz = 0; iz < INDEX_RESOLUTION; iz++) {
      for (let ix = 0; ix < INDEX_RESOLUTION; ix++) {
        const x = -SL.WORLD_RADIUS + (ix + 0.5) * step;
        const z = -SL.WORLD_RADIUS + (iz + 0.5) * step;
        const inside = Math.hypot(x, z) <= SL.WORLD_RADIUS;

        const biome = inside ? biomeAt(x, z) : null;
        cells[iz * INDEX_RESOLUTION + ix] = biome;
        if (biome) buckets[biome.id].push(x, z);
      }
    }

    index = { cells, buckets, step, resolution: INDEX_RESOLUTION };
    return index;
  }

  /** A random point somewhere in this biome, or null if it has no area. */
  function randomPointIn(biome) {
    if (!index) buildIndex();

    const bucket = index.buckets[biome.id];
    if (!bucket || bucket.length === 0) return null;

    const i = Math.floor(SL.random() * (bucket.length / 2)) * 2;
    const jitter = index.step * 0.5;
    return {
      x: bucket[i] + SL.randRange(-jitter, jitter),
      z: bucket[i + 1] + SL.randRange(-jitter, jitter)
    };
  }

  /** Fraction of the sea floor this biome covers, 0-1. */
  function areaShareOf(biome) {
    if (!index) buildIndex();
    const total = BIOMES.reduce((sum, b) => sum + index.buckets[b.id].length, 0);
    return total > 0 ? index.buckets[biome.id].length / total : 0;
  }

  function setSeed(seed) {
    SEED = (seed >>> 0) || 1;
    index = null;
    placeFeatures();
  }

  placeFeatures();

  SL.Biomes = {
    list: BIOMES, byId, biomeAt, floorHeightAt, floorColorAt,
    randomPointIn, areaShareOf, setSeed, buildIndex,
    get index() { return index || buildIndex(); },
    get seamounts() { return seamounts; },
    get kingBasin() { return kingBasin; },
    get whaleGround() { return whaleGround; },
    get farBank() { return farBank; },
    bankRise,
    trenchInfluence, seamountRise
  };
})(window.SL);
