/**
 * The ocean is laid out as concentric rings around the origin: you start in the
 * bright Safe Shallows and every direction you swim takes you somewhere deeper
 * and darker. Ring boundaries are warped by noise so they read as coastlines
 * rather than circles.
 *
 * The sea floor is a *function*, not a mesh. The visible terrain is generated by
 * sampling floorHeightAt(), but so is every gameplay query - where kelp plants,
 * where scrap settles, how a fish avoids the bottom. Nothing raycasts against
 * terrain to find the ground, which is why hundreds of creatures stay cheap.
 */
(function (SL) {
  'use strict';

  // Set per world by SL.Biomes.setSeed. Two worlds with different seeds have
  // genuinely different sea floors and biome coastlines.
  let SEED = 20260912;

  const BIOMES = [
    {
      id: 'shallows', name: 'Safe Shallows',
      outerRadius: 26, floorDepth: 7, roughness: 1.4,
      floorColor: new THREE.Color(0.86, 0.80, 0.60),
      waterColor: new THREE.Color(0.10, 0.55, 0.62),
      fogDensity: 0.012,
      scrapCount: 0, stalkerCount: 0,
      flora: ['seagrass', 'coralFan'], floraPatches: 12
    },
    {
      // The heart of the game: dense kelp, scrap everywhere, stalkers.
      id: 'kelp', name: 'Kelp Forest',
      outerRadius: 52, floorDepth: 15, roughness: 2.6,
      floorColor: new THREE.Color(0.34, 0.38, 0.24),
      waterColor: new THREE.Color(0.06, 0.30, 0.26),
      fogDensity: 0.030,
      scrapCount: 22, stalkerCount: 6,
      flora: ['kelp', 'kelp', 'seagrass'], floraPatches: 26
    },
    {
      id: 'plateau', name: 'Grassy Plateau',
      outerRadius: 74, floorDepth: 21, roughness: 1.9,
      floorColor: new THREE.Color(0.42, 0.52, 0.30),
      waterColor: new THREE.Color(0.05, 0.28, 0.34),
      fogDensity: 0.036,
      scrapCount: 6, stalkerCount: 2,
      flora: ['seagrass', 'seagrass', 'boulder'], floraPatches: 18
    },
    {
      id: 'coral', name: 'Red Coral Reef',
      outerRadius: 92, floorDepth: 27, roughness: 4.2,
      floorColor: new THREE.Color(0.62, 0.26, 0.22),
      waterColor: new THREE.Color(0.14, 0.18, 0.32),
      fogDensity: 0.034,
      scrapCount: 4, stalkerCount: 1,
      flora: ['coralFan', 'coralTube', 'coralTube'], floraPatches: 20
    },
    {
      id: 'boulders', name: 'Boulder Field',
      outerRadius: 106, floorDepth: 34, roughness: 5.2,
      floorColor: new THREE.Color(0.30, 0.31, 0.33),
      waterColor: new THREE.Color(0.06, 0.11, 0.20),
      fogDensity: 0.042,
      scrapCount: 4, stalkerCount: 2,
      flora: ['boulder', 'boulder', 'glowPod'], floraPatches: 16
    },
    {
      // Pink crystal country. The fish here are metal, and the crystals
      // themselves can be cut for quartz.
      id: 'crystal', name: 'Crystal Caverns',
      outerRadius: 126, floorDepth: 40, roughness: 6,
      floorColor: new THREE.Color(0.34, 0.20, 0.30),
      waterColor: new THREE.Color(0.16, 0.06, 0.18),
      fogDensity: 0.038,
      scrapCount: 3, stalkerCount: 1,
      flora: ['crystal', 'crystal', 'boulder'], floraPatches: 22,
      crystalNodes: 26
    },
    {
      id: 'trench', name: 'Deep Trench',
      outerRadius: 148, floorDepth: 56, roughness: 7,
      floorColor: new THREE.Color(0.12, 0.12, 0.15),
      waterColor: new THREE.Color(0.012, 0.035, 0.075),
      fogDensity: 0.075,
      scrapCount: 3, stalkerCount: 0,
      flora: ['glowPod', 'boulder'], floraPatches: 14
    },
    {
      // The hoard. Stalkers haul scrap out here and pile it at the king's feet.
      id: 'kings', name: "King's Domain",
      outerRadius: 168, floorDepth: 64, roughness: 8,
      floorColor: new THREE.Color(0.20, 0.17, 0.12),
      waterColor: new THREE.Color(0.05, 0.04, 0.03),
      fogDensity: 0.055,
      scrapCount: 8, stalkerCount: 3,
      flora: ['boulder', 'glowPod', 'crystal'], floraPatches: 14,
      kingCount: 1
    },
    {
      // Open water at the edge of the map, and the one thing bigger than a king.
      id: 'whale', name: 'Whale Reach',
      outerRadius: 1000, floorDepth: 74, roughness: 5,
      floorColor: new THREE.Color(0.10, 0.14, 0.18),
      waterColor: new THREE.Color(0.02, 0.07, 0.12),
      fogDensity: 0.030,
      scrapCount: 2, stalkerCount: 0,
      flora: ['glowPod', 'boulder'], floraPatches: 10,
      whaleCount: 1
    }
  ];

  const byId = {};
  BIOMES.forEach((b, i) => { b.index = i; byId[b.id] = b; });

  /**
   * Distance from the origin, warped by low-frequency noise. Using this instead
   * of the true radius turns the ring boundaries into organic coastlines.
   */
  function warpedRadius(x, z) {
    const r = Math.hypot(x, z);
    return Math.max(0, r + SL.fbm(x, z, 3, 0.011, 2.1, 0.5, SEED + 41) * 15);
  }

  function biomeAt(x, z) {
    const r = warpedRadius(x, z);
    for (const b of BIOMES) if (r <= b.outerRadius) return b;
    return BIOMES[BIOMES.length - 1];
  }

  /** Which two rings a radius sits between, and how far across the seam it is. */
  function resolveRings(r) {
    const BAND = 9;
    let index = BIOMES.length - 1;
    for (let i = 0; i < BIOMES.length; i++) {
      if (r <= BIOMES[i].outerRadius) { index = i; break; }
    }
    const inner = BIOMES[index];
    const outer = BIOMES[Math.min(index + 1, BIOMES.length - 1)];
    const alpha = inner === outer ? 0 : SL.smoothstep((r - (inner.outerRadius - BAND)) / BAND);
    return { inner, outer, alpha };
  }

  function floorHeightAt(x, z) {
    const r = warpedRadius(x, z);
    const { inner, outer, alpha } = resolveRings(r);

    const depth = SL.lerp(inner.floorDepth, outer.floorDepth, alpha);
    const roughness = SL.lerp(inner.roughness, outer.roughness, alpha);

    // Two noise layers: broad dunes plus fine detail.
    const dunes = SL.fbm(x, z, 4, 0.035, 2.0, 0.5, SEED);
    const detail = SL.fbm(x, z, 3, 0.22, 2.3, 0.45, SEED + 977);

    let y = -depth + dunes * roughness + detail * roughness * 0.28;

    // Carve a canyon through the trench so the deep has real structure.
    if (r > 126 && r < 150) {
      const t = SL.clamp((r - 126) / 24, 0, 1);
      y -= Math.sin(t * Math.PI) * 16;
    }

    // Never let the floor break the surface.
    return Math.min(y, SL.WATER_LEVEL - 2.2);
  }

  const _c = new THREE.Color();
  function floorColorAt(x, z) {
    const r = warpedRadius(x, z);
    const { inner, outer, alpha } = resolveRings(r);
    _c.copy(inner.floorColor).lerp(outer.floorColor, alpha);

    // Mottle the sand so large flat areas do not read as a solid sheet.
    const mottle = SL.fbm(x, z, 2, 0.4, 2, 0.5, SEED + 313) * 0.12;
    return _c.multiplyScalar(1 + mottle);
  }

  /** Inner radius of a ring, for spawning inside it. */
  function innerRadiusOf(biome) {
    return biome.index === 0 ? 0 : BIOMES[biome.index - 1].outerRadius;
  }

  /**
   * A random point inside a biome ring. Ring boundaries are noise-warped, so a
   * point sampled from the ideal ring can land in a neighbour - sample a few
   * times and take the first that agrees.
   */
  function randomPointIn(biome, attempts = 14) {
    const inner = innerRadiusOf(biome);
    const outer = Math.min(biome.outerRadius, SL.WORLD_RADIUS);
    if (outer <= inner) return null;

    for (let i = 0; i < attempts; i++) {
      const angle = Math.random() * Math.PI * 2;
      // Area-uniform radius, so outer rings do not end up sparser.
      const radius = Math.sqrt(SL.randRange(inner * inner, outer * outer));
      const x = Math.cos(angle) * radius;
      const z = Math.sin(angle) * radius;
      if (biomeAt(x, z) === biome) return { x, z };
    }
    return null;
  }

  function setSeed(seed) { SEED = (seed >>> 0) || 1; }

  SL.Biomes = { list: BIOMES, byId, biomeAt, floorHeightAt, floorColorAt, randomPointIn,
    innerRadiusOf, setSeed };
})(window.SL);
